AppVersion: 1.0.0

HTTP:
  Port: ":5000"
  Development: true
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5

GRPC:
  Port: ":7000"
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5

Logger:
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

Nats:
  URL: "localhost:4222"
  ClusterID: microservice
  ClientID: microservice_a

Metrics:
  Port: ":7071"
  Url: "host.docker.internal:7071"
  ServiceName: nats_microservice

Jaeger:
  Host: localhost:6831
  ServiceName: nats_microservice
  LogSpans: false

Redis:
  RedisAddr: "localhost:6379"
  RedisPassword:
  RedisDefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  DB: 0

MailService:
  URL: "localhost:1025"
  From: "alexander.bryksin@yandex.ru"

PostgreSQL:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDBName: mails_db
  PostgresqlSslmode: "disable"
  PgDriver: pgx